---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhook
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-n8n-io-v1alpha1-n8ninstance
  failurePolicy: Fail
  name: mn8ninstance.kb.io
  rules:
  - apiGroups:
    - n8n.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - n8ninstances
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-n8n-io-v1alpha1-n8ninstance
  failurePolicy: Fail
  name: vn8ninstance.kb.io
  rules:
  - apiGroups:
    - n8n.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - n8ninstances
  sideEffects: None