{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "n8n-eks-operator.fullname" . }}-controller-manager-metrics-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-eks-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.monitoring.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: /metrics
    port: https
    scheme: https
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    tlsConfig:
      insecureSkipVerify: true
    {{- with .Values.monitoring.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "n8n-eks-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
      control-plane: controller-manager
  {{- with .Values.monitoring.serviceMonitor.targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}